sudo: false
dist: trusty
language: c
addons:
  apt:
    packages:
      - sbcl
compiler: gcc

script:
  - |
    ./configure --with-x=no && make -j2 2>&1 | tee build.log | \
        sed -n 's/.*\(")compile".*spad\).*/\1/p'
  - |
    make > /dev/null 2>&1 && cd src/input && make -j2 | \
        tee ../../tests.log | sed -n 's/.*tee \(.*output\);.*/\1/p'
  - cd $TRAVIS_BUILD_DIR/src/input && make > /dev/null 2>&1 && ../scripts/test.sh
