# currently there are ALSR issues with SBCL, so Docker can't be used.
sudo: required
dist: trusty
language: c
addons:
  apt:
    packages:
      - sbcl
compiler: gcc

script:
  - |
    ./configure --with-x=no && make -j2 2>&1 | \
        sed -n 's/.*\(")compile".*spad\).*/\1/p'

  - make > /dev/null 2>&1

  - make check -j2 2>&1 | sed -n 's/.*tee \(.*output\);.*/\1/p'

  - make check > /dev/null 2>&1
