sudo: false
dist: trusty
language: c
addons:
  apt:
    packages:
      - sbcl
compiler: gcc

script:
  - ./configure
  - mkdir -p target/x86_64-linux-gnu/lib/ target/x86_64-linux-gnu/bin/
  - cd src/lib && make && cd ../..
  - cd src/graph && make && cd ../..
